name: draw_route_app
description: "A new Flutter project."
version: 1.0.7+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
 # introduction_screen: 3.1.9
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  get: ^4.6.6
  google_fonts: ^4.0.4
  responsive_framework: ^1.4.0
  localization: ^2.1.0
  intl: 0.19.0
  either_dart: ^1.0.0
  dio: ^5.3.2
  image_cropper: 8.1.0
  # responsive_sizer: ^3.0.8
  dotted_line: ^3.2.2
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.7
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.0
  flutter_switch: ^0.3.2
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  awesome_dialog: ^3.1.0
  sizer: ^3.0.4
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  convex_bottom_bar: ^3.2.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_expandable_fab: ^2.3.0
  expandable: ^5.0.1
  url_launcher: ^6.3.1
  flutter_pannable_rating_bar: ^2.7.2+1
  easy_image_viewer: ^1.5.1
  device_info_plus: ^11.0.0
  timer_count_down: ^2.2.0
  pinput: ^5.0.0
  flutter_timer_countdown: ^1.0.7
  flutter_floating_bottom_bar: ^1.2.1+1
  sweet_nav_bar: ^1.0.7
  responsive_navigation_bar: ^5.0.2
  crystal_navigation_bar: ^1.0.0
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  full_screen_image: ^2.0.0
  file_picker: ^8.0.5
  custom_refresh_indicator: ^4.0.1
  mime: ^2.0.0
  flutter_form_builder: ^9.3.0
  easy_stepper: 0.8.3
  dotted_decoration: ^2.0.0
  dropdown_button2: ^2.3.9
  blurrycontainer: ^2.1.0
  syncfusion_flutter_datepicker: ^26.2.14
  flutter_downloader: ^1.11.8
  gallery_saver_plus: ^3.2.1
  icons_launcher: ^3.0.0
  font_awesome_flutter: ^10.8.0
  flutter_lints: ^4.0.0
  flutter_onboarding_slider: ^1.0.11
  expandable_text: 2.3.0
  dropdown_search: ^5.0.3
  animated_custom_dropdown: ^3.1.1
  percent_indicator: ^4.2.4
  http: ^1.2.0
  http_parser: ^4.0.0
  dynamic_height_grid_view: ^0.0.4
  fl_chart: ^0.63.0
  change_app_package_name: ^1.5.0
  flutter_local_notifications: ^17.2.4
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  intl_utils: ^2.8.3
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.0.0




dependency_overrides:
  shared_preferences_android: 2.3.0

#  device_info_plus: ^10.1.2
icons_launcher:
  image_path: "assets/images/nawazi.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/nawazi.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/nawazi.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/nawazi.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/nawazi.png"
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        # - asset: assets/fonts/Bahij-Bold.ttf
        # weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 100
          style: normal

    - family: Century
      fonts:
        - asset: assets/fonts/Century Gothic.ttf

    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf

flutter_assets:
  assets_path: assets/
  output_path: lib/common/constants/
  filename: assets.dart

flutter_intl:
  enabled: true
